name: Missing Spec Rejecter

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Check for Spec changes
      uses: the-nusbaum/version_release_composer@master
      env:
        TOKEN: ${{ secrets.TOKEN }}
        # TRIGGER: ${{ github.event.pull_request.base.ref }} # can use the triggering branch or define a fixed one like this: 'master'
        TRIGGER: master
        REPO_OWNER: the-nusbaum
